name: Test Project
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Intall Node jobs
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install Dependcies
        run: npm ci 
      - name: Run Testss
        run: npm test
  Deploy:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Deploy
        uses: actions/checkout@v3
      - name: Intall Node jobs
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install Dependcies Deploy
        run: npm ci 
      - name: Build Project
        run: npm run build
      - name: Deploy 
        run: echo "Deployeing..."